// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLuL7wnj_XQkgyMB33CR88Av4uRRI3yZs',
    appId: '1:444027429276:web:16638f748d3ed8607fe859',
    messagingSenderId: '444027429276',
    projectId: 'project-6399d',
    authDomain: 'project-6399d.firebaseapp.com',
    databaseURL: 'https://project-6399d-default-rtdb.firebaseio.com',
    storageBucket: 'project-6399d.appspot.com',
    measurementId: 'G-PHT76Y5WJF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAz_cZdjUKLPuI-FqxvahAa8TeL3TuE-LA',
    appId: '1:444027429276:android:e6fab2ab70bb912f7fe859',
    messagingSenderId: '444027429276',
    projectId: 'project-6399d',
    databaseURL: 'https://project-6399d-default-rtdb.firebaseio.com',
    storageBucket: 'project-6399d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGaMdL1QwEEFuT8tQUBmVTMiy3ybL72S4',
    appId: '1:444027429276:ios:8d0166bef5af93b17fe859',
    messagingSenderId: '444027429276',
    projectId: 'project-6399d',
    databaseURL: 'https://project-6399d-default-rtdb.firebaseio.com',
    storageBucket: 'project-6399d.appspot.com',
    iosBundleId: 'com.example.finalproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGaMdL1QwEEFuT8tQUBmVTMiy3ybL72S4',
    appId: '1:444027429276:ios:8d0166bef5af93b17fe859',
    messagingSenderId: '444027429276',
    projectId: 'project-6399d',
    databaseURL: 'https://project-6399d-default-rtdb.firebaseio.com',
    storageBucket: 'project-6399d.appspot.com',
    iosBundleId: 'com.example.finalproject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBFDbxnDMR9Yen2mGlP7IlCcsQFPDrbLrk',
    appId: '1:444027429276:web:679f12b6bfc5e3f27fe859',
    messagingSenderId: '444027429276',
    projectId: 'project-6399d',
    authDomain: 'project-6399d.firebaseapp.com',
    databaseURL: 'https://project-6399d-default-rtdb.firebaseio.com',
    storageBucket: 'project-6399d.appspot.com',
    measurementId: 'G-RG601CG1ZS',
  );
}
